version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-node
      - image: circleci/mysql:5.7.25
        environment:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: unittest_db
          MYSQL_USER: unittest_root
          MYSQL_PASSWORD: unittest_pwd
    working_directory: ~/singnet/marketplace
    environment:
      TRIGGER_BUILD_BRANCH: master
      PYTHONPATH: /home/circleci/singnet/marketplace
    steps:
      - checkout
      - run:
          name: Install MySQL Client
          command: |
            sudo apt-get update
            sudo apt-get install -y mysql-client --no-install-recommends
      - run:
          name: Check Connection & Execute SQL Scripts
          command: |
            /bin/bash ./waitformysql.sh
      - run:
          name: Install Requirements
          command: |
            sudo apt-get update
            sudo apt-get install python3-pip
            python3 -m compileall .
            sudo pip3 install -r requirement.txt
            sudo pip3 install coverage
            export PYTHONPATH=$PATH:`pwd`
      - run:
          name: Run Test Coverage
          command: |
            echo $PYTHONPATH
            python3 -m coverage run ./test/test_contract_api_2.py
            python3 -m coverage report
            python3 -m coverage html

